services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: val-api
    environment:
      - ENVIRONMENT=production
      - API_KEYS=${API_KEYS}
      - FLARESOLVERR_URL=${FLARESOLVERR_URL}
    restart: unless-stopped
    depends_on:
      - flaresolverr
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tracker-api.rule=Host(`val-api.aydenjahola.com`)"
      - "traefik.http.routers.tracker-api.entrypoints=https"
      - "traefik.http.services.tracker-api.loadbalancer.server.port=8000"
    networks:
      - proxy
      - internal

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    ports:
      - "${PORT:-8191}:8191"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Dublin
    networks:
      - internal

networks:
  proxy:
    external: true
  internal:
    external: false
